### PR TITLE
Allow a user to define organisation type at user_type step

### PR DESCRIPTION
**Pull request by reggieb**
Use an ActiveRecord `enum` to define organisation types, as validation has moved to the form object.

### CODE REVIEW

**Comment by autotelik** [comment]
is this sufficient to capture the major differences between organisation types ?

for example

class Partnership < DigitalServicesCore::Organisation
      has_many :partner_contacts

Are whatever  savings you are making in the state machine worth it, considering we are once again invalidating everything from WEX  models, page objects, factories, tests  ?

**Comment by reggieb** [comment]
The partnership is the only instance I can think of when there is a difference between organisation types. As this app doesn't validate at the model level, all the benefits of using a enum field outweighs the issue of having to deal with this one case IMO.

**Comment by autotelik** [comment]
what benefits out weigh the flexibility of proper OO modelling ? 

This was the code to create all the next evens for the OrgType branch .. can't see how an enum instead of classes would make that shorter or more understandable
```
    WasteExemptionsShared::OrganisationTypes.types_display_list.each_with_index do |t, i|
      org_type_state = WasteExemptionsShared::OrganisationTypes.type_names_list[i].to_sym
      transition from: :choosing_organisation_type, to: org_type_state, on: :next,
                 if: ->(e) do
                   e.organisation && e.organisation.sti_class == t
                 end
    end
```

but since your doing the branching code, go for it :ship:

**Comment by woodpigeon** [comment]
I'm happy to go this way for now as it removes the STI complexity and we'll have use a simpler approach to adding the partnership relationship which is the only thing this approach leaves unsolved :ship:

**Comment by reggieb** [comment]
rebased

**Pull request merged**
