### PR TITLE
RIP 57: Grid reference (Capture location)

### PR DESCRIPTION
**Pull request by reggieb**
Relates to Jira [57](https://eaflood.atlassian.net/browse/RIP-57)

### CODE REVIEW

**Comment by reggieb** [comment]
[Prototype page](http://river-permissions.herokuapp.com/version_2/location/grid_reference_2) is broken at the moment so put on hold.

**Comment by reggieb** [comment]
Prototype has been fixed - but still some debate on what users will be asked to input (grid ref, and/or eastings and northings) - so still on hold.

**Comment by reggieb** [comment]
Rebased

**Comment by woodpigeon** [comment]
Looks good to me :ship: it

**Comment by reggieb** [comment]
Rebased

**Pull request merged**
