### PR TITLE
Tidy up check location page - RIP-53

### PR DESCRIPTION
**Pull request by autotelik**
tidy up locale locations
ensure validation message  match version 1.4 of content doc

### CODE REVIEW

**Comment by autotelik** [comment]
:eyes:

**Comment by reggieb** [comment]
Is there something wrong with the rubocop settings being used here? This pull request seems to be changing all the double quotes back to single quotes.

**Comment by autotelik** [comment]
highly probable, I slacked some  issues I had with before_commit, but have also seen funnies where rubocop run externally behaves differently to rubocop run by before_commit, even though AFAIK they should pick up the same .yaml file 

I can see the .yaml file contains 

# There are no relative performance improvements using '' over "", therefore we believe there is more
# value in using "" for all strings irrespective of whether string interpolation is used
Style/StringLiterals:
  EnforcedStyle: double_quotes

But rubocop passes

**Comment by autotelik** [comment]
Ok I cloned the repo again totally fresh, install before_commit  
[09:09:56:rubyuser:~/SoftwareDev/git/flood-risk-engine] >gem install before_commit
Successfully installed before_commit-0.6.1

then switching to this branch :
```
>git checkout feature/rip-53-tidy_up_check_location 
Branch feature/rip-53-tidy_up_check_location set up to track remote branch feature/rip-53-tidy_up_check_location from origin.
Switched to a new branch 'feature/rip-53-tidy_up_check_location'
Problem loading '.overcommit_gems.rb': Could not find rake-11.1.2 in any of the sources
Try running:
bundle install --gemfile=.overcommit_gems.rb
```

**Comment by autotelik** [comment]
Adding rake manually to the Gemfile does not fix the issues

gem "rake", "11.1.2"

**Comment by reggieb** [comment]
What happens if you `rake app:before_commit:run` after checking out the feature branch?

**Pull request merged**
