### PR TITLE
RIP-73 - location name specs

### PR DESCRIPTION
**Pull request by autotelik**
Regression in code base was not caught, these try to address but suspect validations still not properly tested through whole stack.

Prefer bringing in proper feature specs which did catch the regression

### CODE REVIEW

**Comment by autotelik** [comment]
:eyes:

**Comment by reggieb** [comment]
I think the `local_authority_spec.rb` should be at `spec/controllers/flood_risk_engine/enrollments/steps_controller/local_authority_spec.rb` as it is describing some of the behaviour of the steps controller.

**Comment by reggieb** [comment]
Otherwise, looks good to me.

**Comment by autotelik** [comment]
I don't think there are really testing the controller, which should be transparent to us, these are testing the enrollment gets built, validates etc hence location

**Comment by reggieb** [comment]
The start of the spec is:
```
require "rails_helper"
module FloodRiskEngine
  describe Enrollments::StepsController, type: :controller do
```

**Comment by autotelik** [comment]
develop/spec/controllers/flood_risk_engine/enrollments/steps_controller_spec.rb

**Pull request merged**
